In [53]:
import pandas as pd

# Load the Excel file
file_path = '/content/classes.xlsx'  # Replace with your file path
df = pd.read_excel(file_path)


df

      Class Participant    Manager
0   Class 1         Bob       Luke
1   Class 1       Sally     Donald
2   Class 1        Bill        Tom
3   Class 1        Fred        Bob
4   Class 1         Max      Sasha
5   Class 1        John        Ian
6   Class 2        Greg        Joe
7   Class 2         Sam        Max
8   Class 2         Pat       Mary
9   Class 2        Mark        Sam
10  Class 2       Steve       Jose
11  Class 3      Rhonda    William
12  Class 3         Tim       Fred
13  Class 3        Will    Patrick
14  Class 3        Lucy       John
15  Class 3        Judy  Elizabeth
16  Class 3      Robert      Harry

In [64]:
# Create an empty list to store the matches
matches = []

# Iterate over each unique class in the DataFrame
for class_name in df['Class'].unique():
    # Filter DataFrame for the current class
    class_df = df[df['Class'] == class_name]

    # Iterate over each participant in the current class
    for participant in class_df['Participant'].unique():
        # Find the manager of the participant within the current class
        manager_df = class_df[class_df['Manager'] == participant]['Participant'] # Get the DataFrame of managers for the current participant
        manager = manager_df.iloc[0] if not manager_df.empty else None # Check if the DataFrame is empty before accessing the first element

        matches.append({'Class': class_name,
                       'Participant': manager,
                       'Manager in class': participant})

# Create a DataFrame from the matches list
matches_df = pd.DataFrame(matches)

# Print the DataFrame
print(matches_df)

      Class Participant Manager in class
0   Class 1        Fred              Bob
1   Class 1        None            Sally
2   Class 1        None             Bill
3   Class 1        None             Fred
4   Class 1        None              Max
5   Class 1        None             John
6   Class 2        None             Greg
7   Class 2        Mark              Sam
8   Class 2        None              Pat
9   Class 2        None             Mark
10  Class 2        None            Steve
11  Class 3        None           Rhonda
12  Class 3        None              Tim
13  Class 3        None             Will
14  Class 3        None             Lucy
15  Class 3        None             Judy
16  Class 3        None           Robert

In [32]:
print(matches_df)

      Class Participant    Manager
0   Class 1         Bob       Luke
1   Class 1       Sally     Donald
2   Class 1        Bill        Tom
3   Class 1        Fred        Bob
4   Class 1         Max      Sasha
5   Class 1        John        Ian
6   Class 2        Greg        Joe
7   Class 2         Sam        Max
8   Class 2         Pat       Mary
9   Class 2        Mark        Sam
10  Class 2       Steve       Jose
11  Class 3      Rhonda    William
12  Class 3         Tim       Fred
13  Class 3        Will    Patrick
14  Class 3        Lucy       John
15  Class 3        Judy  Elizabeth
16  Class 3      Robert      Harry