In [1]:
import pandas as pd
df = pd.DataFrame({'flight_start': ['2019-02-04 13:15:00', 
                                       '2020-01-01 21:30:00', 
                                       '2021-10-28 02:00:00'],
                   'flight_length': [7, 21.5, 30],
                   'return_start': ['01/03/2019 10:00:00', 
                                   '11/01/2020 20:50:00', 
                                   '05/11/2021 08:20:00']})
df

          flight_start  flight_length         return_start
0  2019-02-04 13:15:00            7.0  01/03/2019 10:00:00
1  2020-01-01 21:30:00           21.5  11/01/2020 20:50:00
2  2021-10-28 02:00:00           30.0  05/11/2021 08:20:00

In [2]:
df['flight_start'] = pd.to_datetime(df['flight_start'])
df['flight_length'] = pd.to_timedelta(df['flight_length'], 'h')
df['return_start'] = pd.to_datetime(df['return_start'], 
                                    format='%d/%m/%Y %H:%M:%S')
df

         flight_start   flight_length        return_start
0 2019-02-04 13:15:00 0 days 07:00:00 2019-03-01 10:00:00
1 2020-01-01 21:30:00 0 days 21:30:00 2020-01-11 20:50:00
2 2021-10-28 02:00:00 1 days 06:00:00 2021-11-05 08:20:00

In [3]:
df['duration'] = df['return_start'] - df['flight_start']
df

         flight_start   flight_length        return_start         duration
0 2019-02-04 13:15:00 0 days 07:00:00 2019-03-01 10:00:00 24 days 20:45:00
1 2020-01-01 21:30:00 0 days 21:30:00 2020-01-11 20:50:00  9 days 23:20:00
2 2021-10-28 02:00:00 1 days 06:00:00 2021-11-05 08:20:00  8 days 06:20:00

In [4]:
df['flight_end'] = df['flight_start'] + df['flight_length']
df[['flight_start', 'flight_length', 'flight_end']]

         flight_start   flight_length          flight_end
0 2019-02-04 13:15:00 0 days 07:00:00 2019-02-04 20:15:00
1 2020-01-01 21:30:00 0 days 21:30:00 2020-01-02 19:00:00
2 2021-10-28 02:00:00 1 days 06:00:00 2021-10-29 08:00:00